### ISSUE TITLE
Completion in the middle of a word

### ISSUE THREAD

**Issue by wiruzx** [nathankot/company-sourcekit#10]
Example:

``` swift
self.doSome // Doesn't complete me here
```

``` swift
self. // If I ask to complete me here, it will show "doSomething" completion
```

**Comment by nathankot** [comment]
This was working at some point, perhaps not anymore. I'll check it out!

**Comment by nathankot** [comment]
@wiruzx this seems to be working for me (see attached gif)
Perhaps it is just being slow? Can you please enable `company-sourcekit-verbose` and check what prefix is being used by company in the `*Messages*` buffer? In your case the prefix should be 'doSome'

![example](https://cloud.githubusercontent.com/assets/1400871/11624733/12a9e23c-9d19-11e5-9cdc-858e91c7700f.gif)

**Comment by wiruzx** [comment]
Hmm, it seems to be working right now. Probably the reason of this was something else. Thanks for response!
