### ISSUE TITLE
Question: How to make company-sourcekit turn on automatically?

### ISSUE THREAD

**Issue by wiruzx** [nathankot/company-sourcekit#15]
Company mode not being automatically enable company-sourcekitten, instead it turn on some kind of "general" mode, when it's trying to complete me based not on sourcekitten.

When I type a few chars, I got:

![](http://i.imgur.com/X6hp9i8.png)

And only when I run `company-sourcekit`, the real completion is showing up:

![](http://i.imgur.com/egKD55P.png)

Could you please point me at what I am doing wrong?

**Comment by terhechte** [comment]
Can you try adding this to your `init.el` or executing it in the `*scratch*` buffer:

```
(add-hook 'swift-mode-hook (lambda ()
                          (set (make-local-variable 'company-backends) '(company-sourcekit))
                          (company-mode)))
```

And then re-load `swift-mode` / `company-mode` and see if that works?

**Comment by wiruzx** [comment]
@terhechte Yes! Thanks a lot!

**Comment by nathankot** [comment]
I will add this step to the installation section :)
