### ISSUE TITLE
Why not silent the message when writing to the tmp file?

### ISSUE THREAD

**Issue by galeo** [nathankot/company-sourcekit#23]
Hi, @nathankot 

I've seen the latest two commits (6c0c783 and 0c3ccf9) by you trying to silent the writing message and then reverted. Maybe the code `(write-region (point-min) (point-max) tmpfile 'silent)` in 6c0c783 was wrong:

The arguments for `write-region`:
> `(write-region START END FILENAME &optional APPEND VISIT LOCKNAME MUSTBENEW)`

The optional fourth argument `APPEND` should be set to `nil`. The right code should be:
`(write-region (point-min) (point-max) tmpfile nil 'silent)` .

Could we turn off the writing message which is really annoying?

Thanks and happy new year :)

**Comment by nathankot** [comment]
@galeo I'm not sure why I reverted that commit, I remember it broke something under a certain condition.

It seems like you've managed to get it working though? Feel free to submit a pull-request for this fix - I'd much prefer the community contribute than just make issues for these things :)

**Comment by galeo** [comment]
Thanks and I'm glad to make a contribution next time :)
