### ISSUE TITLE
xcodebuild

### ISSUE THREAD

**Issue by nicolas4d** [nathankot/company-sourcekit#32]
[sourcekit] process message: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance[sourcekit] process message: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

how can i fix this? bros.

**Comment by nathankot** [comment]
Hey @nicolas4d you'll need to install xcode and (maybe) run `xcode-select --install` again

**Comment by nicolas4d** [comment]
@nathankot 
thanks for your help.
I used this command
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/ 
and it's worked.
